name: Unpack monorepo ZIP
on: workflow_dispatch          # run it manually once

permissions:
  contents: write              # allow the job to push commits

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with: { fetch-depth: 0 }

      - name: Unzip any root-level ZIPs
        run: |
          set -e
          shopt -s nullglob
          for z in *.zip; do
            echo "▶ Unpacking $z"
            unzip -o "$z" -d .
            git rm "$z"
          done

      - name: Commit unpacked source
        run: |
          git config user.name  "unzip-bot"
          git config user.email "unzip-bot@users.noreply.github.com"
          git add .
          git commit -m "Unpack monorepo archive 🚀" || echo "Nothing to commit"
          git push origin HEAD
