name: Unpack monorepo ZIP
on:
  workflow_dispatch:       # run manually from Actions tab
jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Unzip archive
        run: |
          unzip -o proof_nft_monorepo.zip
          # If you really want backend / frontend split instead, swap the file names.
          rm -f proof_nft_monorepo.zip proof_nft_backend.zip proof_nft_frontend.zip

      - name: Commit unpacked source
        run: |
          git config user.name  "unzip-bot"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Unpack monorepo archive 🚀" || echo "Nothing to commit"
          git push
